<img src="images/usm.jpg" width="480" height="240" align="left"/>

# MAT281 - Laboratorio N°02

## Objetivos de la clase

* Reforzar los conceptos básicos de numpy.

## Contenidos

* [Problema 01](#p1)
* [Problema 02](#p2)
* [Problema 03](#p3)

<a id='p1'></a>

## Problema 01

Una **media móvil simple** (SMA) es el promedio de los últimos $k$ datos anteriores, es decir, sea $a_1$,$a_2$,...,$a_n$ un arreglo $n$-dimensional, entonces la SMA se define por:

$$sma(k) =\dfrac{1}{k}(a_{n}+a_{n-1}+...+a_{n-(k-1)}) = \dfrac{1}{k}\sum_{i=0}^{k-1}a_{n-i}  $$ 


Por otro lado podemos definir el SMA con una venta móvil de $n$ si el resultado nos retorna la el promedio ponderado avanzando de la siguiente forma:

* $a = [1,2,3,4,5]$, la SMA con una ventana de $n=2$ sería:


    * sma(2): [mean(1,2),mean(2,3),mean(3,4)] = [1.5, 2.5, 3.5, 4.5]
    * sma(3): [mean(1,2,3),mean(2,3,4),mean(3,4,5)] = [2.,3.,4.]


Implemente una función llamada `sma` cuyo input sea un arreglo unidimensional $a$ y un entero $n$, y cuyo ouput retorne el valor de la media móvil simple sobre el arreglo de la siguiente forma:

* **Ejemplo**: *sma([5,3,8,10,2,1,5,1,0,2], 2)* = $[4. , 5.5, 9. , 6. , 1.5, 3. , 3. , 0.5, 1. ]$

En este caso, se esta calculando el SMA para un arreglo con una ventana de $n=2$.

**Hint**: utilice la función `numpy.cumsum`

In [26]:
import numpy as np
def sma(a:np.array, n:int)->list:
    
    """
    sma(a,n)

    Calcula el promedio considerando n datos sobre un arreglo a

    Parameters
    ----------
    a : np.array 
        Arreglo unidimensional de números.
    
    n : int
        Número de terminos.

    Returns
    -------
    output : list
        lista con los promedios calculados considerando n términos.
        
    Examples
    --------
    >>> sma([5,3,8,10,2,1,5,1,0,2], 2)
    [4.,5.5,9.,6.,1.5,3.,3.,0.5,1.]
    
    """
    
    cum_a= np.cumsum(a) #retorna un arreglo de la suma acumulada de los numeros en el arreglo
    arr=np.empty(len(a)-n+1, dtype=float)
    arr[0]=cum_a[n-1]/n
    for i in range(0,len(cum_a)-n):
        arr[i+1]=(cum_a[i+n]-cum_a[i])/n
        
    return list(arr)


print(sma([5,3,8,10,2,1,5,1,0,2], n=2))

[4.0, 5.5, 9.0, 6.0, 1.5, 3.0, 3.0, 0.5, 1.0]


<a id='p2'></a>

## Problema 02

La función **strides($a,n,p$)**, corresponde a transformar un arreglo unidimensional $a$ en una matriz de $n$ columnas, en el cual las filas se van construyendo desfasando la posición del arreglo en $p$ pasos hacia adelante.

* Para el arreglo unidimensional $a$ = [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], la función strides($a,4,2$), corresponde a crear una matriz de $4$ columnas, cuyos desfaces hacia adelante se hacen de dos en dos. 

El resultado tendría que ser algo así:$$\begin{pmatrix}
 1& 2 &3 &4 \\ 
 3&  4&5&6 \\ 
 5& 6 &7 &8 \\ 
 7& 8 &9 &10 \\ 
\end{pmatrix}$$


Implemente una función llamada `strides(a,4,2)` cuyo input sea un arreglo unidimensional y retorne la matriz de $4$ columnas, cuyos desfaces hacia adelante se hacen de dos en dos. 

* **Ejemplo**: *strides($a$,4,2)* =$\begin{pmatrix}
 1& 2 &3 &4 \\ 
 3&  4&5&6 \\ 
 5& 6 &7 &8 \\ 
 7& 8 &9 &10 \\ 
\end{pmatrix}$


In [25]:
def strides(a:np.array, n:int, p:int)->np.array:
    
    """
    strides(a,n,p)

    Transforma un arreglo unidimensional en una matriz de n columnas, considerando elementos con desfase p

    Parameters
    ----------
    a : np.array 
        Arreglo unidimensional de números.
    
    n : int
        Número de terminos.
        
    p : int
        Número de desfase.

    Returns
    -------
    output : np.array
        matriz de n columnas con desfase p.
        
    Examples
    --------
    >>> strides([1, 2, 3, 4, 5, 6, 7, 8, 9, 10],4,2)
    [[ 1.  2.  3.  4.]
     [ 3.  4.  5.  6.]
     [ 5.  6.  7.  8.]
     [ 7.  8.  9. 10.]]
    
    """
    arr=np.empty([(len(a)-n)//p+1,n])
    k=0
    for i in range(0,(len(a)-n)//p+1):
        for j in range(n):
            arr[i][j]=a[j+k]
        k+=p              
        
    return arr
print(strides([1, 2, 3, 4, 5, 6, 7, 8, 9, 10],4,2))

[[ 1.  2.  3.  4.]
 [ 3.  4.  5.  6.]
 [ 5.  6.  7.  8.]
 [ 7.  8.  9. 10.]]


<a id='p3'></a>

## Problema 03


Un **cuadrado mágico** es una matriz de tamaño $n \times n$ de números enteros positivos tal que 
la suma de los números por columnas, filas y diagonales principales sea la misma. Usualmente, los números empleados para rellenar las casillas son consecutivos, de 1 a $n^2$, siendo $n$ el número de columnas y filas del cuadrado mágico.

Si los números son consecutivos de 1 a $n^2$, la suma de los números por columnas, filas y diagonales principales 
es igual a : $$M_{n} = \dfrac{n(n^2+1)}{2}$$
Por ejemplo, 

* $A= \begin{pmatrix}
 4& 9 &2 \\ 
 3&  5&7 \\ 
 8& 1 &6 
\end{pmatrix}$,
es un cuadrado mágico.

* $B= \begin{pmatrix}
 4& 2 &9 \\ 
 3&  5&7 \\ 
 8& 1 &6 
\end{pmatrix}$, no es un cuadrado mágico.

Implemente una función llamada `es_cudrado_magico` cuyo input sea una matriz cuadrada de tamaño $n$ con números consecutivos de $1$ a $n^2$ y cuyo ouput retorne *True* si es un cuadrado mágico o 'False', en caso contrario

* **Ejemplo**: *es_cudrado_magico($A$)* = True, *es_cudrado_magico($B$)* = False

**Hint**: Cree una función que valide la mariz es cuadrada y  que sus números son consecutivos del 1 a $n^2$.

In [24]:
#Función que verifica si la matriz es cuadrada y tiene números consecutivos de 1 a n^2
def cuadrada(a:np.array)->bool:
    
    """
    cuadrada(a)

    Verifica si una matriz es cuadrada con números consecutivos desde 1 a n^2.

    Parameters
    ----------
    a : np.array 
        Matriz de números.

    Returns
    -------
    output : bool
        Retorna True si la matriz es cuadrada y tiene numeros consecutivos de 1 a n^2. 
        Donde n es el número de filas de la matriz.
        Retorna False si alguna de las condiciones no se cumple
        
    Examples
    --------
    >>> cuadrada(np.array([[4, 9, 2], [3, 5, 7],[8, 1, 6]]))
    True
    
    >>> cuadrada(np.array([[4, 9, 2], [3, 5, 7]))
    False
    
    """
    
    
    (n,m)=a.shape
    if n==m:
        flag=True
        k=1
        while flag and k<=n**2:
            flag=False
            for row in a:
                if k in row:
                    flag=True
            k+=1
        return flag
                

    else:
        return False
    
    
def es_cuadrado_magico(a:np.array)->bool:
    
    
    """
    es_cuadrado_magico(a)

    Verifica si una matriz cuadrada con números consecutivos desde 1 a n^2, es cuadrado mágico.
    Donde n es el número de filas de la matriz

    Parameters
    ----------
    a : np.array 
        Matriz de números.

    Returns
    -------
    output : bool
        Retorna True si la matriz es cuadrado mágico o False si no lo es.
        
    Examples
    --------
    >>> es_cuadrado_magico(np.array([[4, 9, 2], [3, 5, 7],[8, 1, 6]]))
    True
    
    >>> es_cuadrado_magico(np.array([[4, 2, 9], [3, 5, 7],[8, 1, 6]]))
    False
    
    """
    
    if cuadrada(a)==True:
        n= np.size(a, 0) #entrega el numero de filas de la matriz a
        sum= n*(n**2+1)/2
        for i in range(0,len(a.sum(axis=0))): 
            if a.sum(axis=0)[i]!= sum:
                return False
            
        for i in range(0,len(a.sum(axis=1))): 
            if a.sum(axis=1)[i]!= sum:
                return False
            
        if np.trace(a)!= sum:
            return False
        
        if np.trace(np.fliplr(a)) != sum:
            return False
        
        return True     
    else: 
        return False
    
print(es_cuadrado_magico(np.array([[4, 9, 2], [3, 5, 7],[8, 1, 6]])))

True
